# Generated by Django 3.0.3 on 2020-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='femalesinger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabatletterofsingers', models.CharField(max_length=50)),
                ('namesofsingers', models.CharField(max_length=50)),
            ],
        ),
    ]
