# Generated by Django 3.0.3 on 2020-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalesinger',
            name='linkofsinger',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
