# Generated by Django 3.0.3 on 2020-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasong', '0002_femalesinger_linkofsinger'),
    ]

    operations = [
        migrations.CreateModel(
            name='malesinger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabatletterofsingers', models.CharField(max_length=50)),
                ('namesofsingers', models.CharField(max_length=50)),
                ('linkofsinger', models.CharField(max_length=150)),
            ],
        ),
    ]
